site_name: AoE2 Scenario Parser Documentation
site_url: https://ksneijders.github.io/AoE2ScenarioParser/
docs_dir: docs/
repo_name: "AoE2ScenarioParser"
repo_url: "https://github.com/KSneijders/AoE2ScenarioParser"
use_directory_urls: true

plugins:
    - search
    - mkdocstrings:
        custom_templates: resources/docs/templates/
        default_handler: python
        handlers:
          python:
            paths: [.]
            options:
              # Options from: https://mkdocstrings.github.io/python/usage/
              show_if_no_docstring: true
              show_category_heading: true
              docstring_style: google
              show_source: true  # Show source code
              show_bases: true  # Show parent classes
              show_submodules: true  # Show the subclasses
              filters: ["!^_[^_]"]
              show_signature: false
              show_signature_annotations: false


watch:
- AoE2ScenarioParser
- docs
- resources/docs

nav:
  - AoE2SP:
    - About:                "index.md"
    - Installation:         "installation.md"
    - Getting Started:      "getting_started.md"
    - Hello World:          "hello_world.md"
    - Support:              "support.md"
  - Cheatsheets:
    - AreaPattern:          "cheatsheets/area.md"
    - Data Triggers:        "cheatsheets/data_triggers.md"
    - Datasets:             "cheatsheets/datasets.md"
    - Message:              "cheatsheets/message.md"
    - Map:                  "cheatsheets/map.md"
    - Players:              "cheatsheets/players.md"
    - Triggers:             "cheatsheets/triggers.md"
    - Units:                "cheatsheets/units.md"
    - XS Script:            "cheatsheets/xs.md"
    - XS Check:            "cheatsheets/xs_check.md"
  - Examples:
    - Intro:                "examples/examples.md"
    - Operations:           "examples/operations.md"
    - Triggers:             "examples/triggers.md"
  - Community:
    - Guides and Resources: "community/resources.md"
    - Tools:                "community/tools.md"
    - Projects:             "community/projects.md"
  - API Docs:
    - AoE2Scenario:         "api_docs/aoe2_scenario.md"
    - AoE2DEScenario:       "api_docs/aoe2_de_scenario.md"
    - Settings:             "api_docs/settings.md"
    - Map:
      - MapManager:         "api_docs/map/map_manager.md"
      - MapManagerDE:       "api_docs/map/map_manager_de.md"
      - TerrainTile:        "api_docs/map/terrain_tile.md"
    - Messages:
      - MessageManager:     "api_docs/messages/message_manager.md"
    - Options:
      - OptionManager:     "api_docs/options/option_manager.md"
    - Player:
      - PlayerManager:      "api_docs/player/player_manager.md"
      - PlayerData:         "api_docs/player/player.md"
    - Trigger:
      - TriggerManager:     "api_docs/trigger/trigger_manager.md"
      - TriggerManagerDE:   "api_docs/trigger/trigger_manager_de.md"
      - Trigger:            "api_docs/trigger/trigger.md"
      - Effects:
        - Effect:           "api_docs/trigger/effects/effect.md"
        - NewEffect:        "api_docs/trigger/effects/new_effect.md"
      - Conditions:
        - Condition:        "api_docs/trigger/conditions/condition.md"
        - NewCondition:     "api_docs/trigger/conditions/new_condition.md"
      - Variable:           "api_docs/trigger/variable.md"
      - TriggerSelect:      "api_docs/trigger/trigger_select.md"
      - TriggerCeLock:      "api_docs/trigger/trigger_ce_lock.md"
    - Units:
      - UnitManager:        "api_docs/units/unit_manager.md"
      - UnitManagerDE:      "api_docs/units/unit_manager_de.md"
      - Unit:               "api_docs/units/unit.md"
    - XS:
      - XsManager:          "api_docs/xs/xs_manager_de.md"
      - XsCheck:            "api_docs/xs/xs_check.md"
    - Support:
      - Area:               "api_docs/support/area.md"
      - AreaAttr:           "api_docs/support/area_attr.md"
      - AreaState:          "api_docs/support/area_state.md"
    - Datasets:
      - ActionType:           "api_docs/datasets/trigger_lists/action_type.md"
      - Age:                  "api_docs/datasets/trigger_lists/age.md"
      - AttackStance:         "api_docs/datasets/trigger_lists/attack_stance.md"
      - Attribute:            "api_docs/datasets/trigger_lists/attribute.md"
      - BlastLevel:           "api_docs/datasets/trigger_lists/blast_level.md"
      - BlockageClass:        "api_docs/datasets/trigger_lists/blockage_class.md"
      - BuildingInfo:         "api_docs/datasets/buildings.md"
      - ButtonLocation:       "api_docs/datasets/trigger_lists/button_location.md"
      - ChargeEvent:          "api_docs/datasets/trigger_lists/charge_event.md"
      - ChargeType:           "api_docs/datasets/trigger_lists/charge_type.md"
      - Civilization:         "api_docs/datasets/civilization.md"
      - ColorId:              "api_docs/datasets/color_id.md"
      - ColorMood:            "api_docs/datasets/trigger_lists/color_mood.md"
      - CombatAbility:        "api_docs/datasets/trigger_lists/combat_ability.md"
      - Comparison:           "api_docs/datasets/trigger_lists/comparison.md"
      - ConditionId:          "api_docs/datasets/conditions.md"
      - DamageClass:          "api_docs/datasets/trigger_lists/damage_class.md"
      - DifficultyLevel:      "api_docs/datasets/trigger_lists/difficulty_level.md"
      - DiplomacyState:       "api_docs/datasets/trigger_lists/diplomacy_state.md"
      - EffectId:             "api_docs/datasets/effects.md"
      - FogVisibility:        "api_docs/datasets/trigger_lists/fog_visibility.md"
      - GarrisonType:         "api_docs/datasets/trigger_lists/garrison_type.md"
      - HeroInfo:             "api_docs/datasets/heroes.md"
      - HeroStatusFlag:       "api_docs/datasets/trigger_lists/hero_status_flag.md"
      - Hotkey:               "api_docs/datasets/trigger_lists/hotkey.md"
      - ObjectAttribute:      "api_docs/datasets/trigger_lists/object_attribute.md"
      - ObjectClass:          "api_docs/datasets/trigger_lists/object_class.md"
      - ObjectState:          "api_docs/datasets/trigger_lists/object_state.md"
      - ObjectType:           "api_docs/datasets/trigger_lists/object_type.md"
      - ObstructionType:      "api_docs/datasets/trigger_lists/obstruction_type.md"
      - OcclusionMode:        "api_docs/datasets/trigger_lists/occlusion_mode.md"
      - Operation:            "api_docs/datasets/trigger_lists/operation.md"
      - OtherInfo:            "api_docs/datasets/other.md"
      - PanelLocation:        "api_docs/datasets/trigger_lists/panel_location.md"
      - PlayerColorId:        "api_docs/datasets/player_color_id.md"
      - PlayerId:             "api_docs/datasets/players.md"
      - ProjectileHitMode:    "api_docs/datasets/trigger_lists/projectile_hit_mode.md"
      - ProjectileInfo:       "api_docs/datasets/projectiles.md"
      - ProjectileSmartMode:  "api_docs/datasets/trigger_lists/projectile_smart_mode.md"
      - ProjectileVanishMode: "api_docs/datasets/trigger_lists/projectile_vanish_mode.md"
      - ScenarioVariant:      "api_docs/datasets/scenario_variant.md"
      - SecondaryGameMode:    "api_docs/datasets/trigger_lists/secondary_game_mode.md"
      - SelectionEffect:      "api_docs/datasets/trigger_lists/selection_effect.md"
      - StartingAge:          "api_docs/datasets/starting_age.md"
      - TechInfo:             "api_docs/datasets/techs.md"
      - TechnologyState:      "api_docs/datasets/trigger_lists/technology_state.md"
      - TerrainId:            "api_docs/datasets/terrains.md"
      - TerrainRestrictions:  "api_docs/datasets/trigger_lists/terrain_restrictions.md"
      - TimeUnit:             "api_docs/datasets/trigger_lists/time_unit.md"
      - UnitAIAction:         "api_docs/datasets/trigger_lists/unit_ai_action.md"
      - UnitInfo:             "api_docs/datasets/units.md"
      - UnitTrait:            "api_docs/datasets/trigger_lists/unit_trait.md"
      - VictoryCondition:     "api_docs/datasets/trigger_lists/victory_condition.md"
      - VictoryTimerType:     "api_docs/datasets/trigger_lists/victory_timer_type.md"
      - VisibilityState:      "api_docs/datasets/trigger_lists/visibility_state.md"
      - Support:
        - InfoDatasetBase:    "api_docs/datasets/support/info_dataset_base.md"


markdown_extensions:
  - admonition                # Create not and warning boxes        https://squidfunk.github.io/mkdocs-material/reference/admonitions/#admonition
  - pymdownx.caret            # Handling sub- and superscripts      https://facelessuser.github.io/pymdown-extensions/extensions/caret/
  - pymdownx.mark             # Highlighting of text                https://facelessuser.github.io/pymdown-extensions/extensions/mark/
  - pymdownx.tilde            # Strikethrough of text               https://facelessuser.github.io/pymdown-extensions/extensions/tilde/
  - pymdownx.keys             # Add styling keyboard keys           https://facelessuser.github.io/pymdown-extensions/extensions/keys/
  - pymdownx.tabbed           # Tabs                                https://facelessuser.github.io/pymdown-extensions/extensions/tabbed/
  - pymdownx.details          # Collapsable elements                https://facelessuser.github.io/pymdown-extensions/extensions/details/
  - pymdownx.highlight:       # Highlighting code blocks            https://facelessuser.github.io/pymdown-extensions/extensions/highlight/
      linenums: true
  - pymdownx.emoji:           # Emojis                              https://facelessuser.github.io/pymdown-extensions/extensions/emoji/
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite     # Inline code highlighting            https://facelessuser.github.io/pymdown-extensions/extensions/inlinehilite/
  - pymdownx.superfences      # Complicated code fences             https://facelessuser.github.io/pymdown-extensions/extensions/superfences/
  - pymdownx.smartsymbols     # Creating special characters         https://facelessuser.github.io/pymdown-extensions/extensions/smartsymbols/
  - pymdownx.arithmatex:      # Preserve LaTeX math equations       https://facelessuser.github.io/pymdown-extensions/extensions/arithmatex/
      generic: true
  - pymdownx.tasklist:        # Creating Check-able tasklist        https://facelessuser.github.io/pymdown-extensions/extensions/tasklist/
      custom_checkbox: true
      clickable_checkbox: true
  - toc:
      permalink: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - _assets/js/api_docs_toc.js

extra_css:
  - _assets/css/api_docs_extra.css
  - _assets/css/api_docs_toc.css

theme:
  name: material
  language: en
#  favicon: imgs/code.svg
#  icon:
#    logo: fontawesome/solid/code
  features:
    - navigation.tabs
    - search.suggest
    - search.highlight
    - search.share
    - navigation.expand
  font:
    text: Roboto
    code: Fira Code
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode