site_name: AoE2 Scenario Parser Documentation
site_url: https://ksneijders.github.io/AoE2ScenarioParser/
docs_dir: docs/
repo_name: "AoE2ScenarioParser"
repo_url: "https://github.com/KSneijders/AoE2ScenarioParser"
use_directory_urls: true

plugins:
    - search
    - mkdocstrings:
        custom_templates: resources/docs/templates
        default_handler: python
        handlers:
          python:
            options:
              # Options from: https://mkdocstrings.github.io/python/usage/
              show_if_no_docstring: true
              show_category_heading: true
              docstring_style: google
              show_source: true  # Show source code
              show_bases: true  # Show parent classes
              filters: ["!^_[^_]"]
              show_signature: false
              show_signature_annotations: false


watch:
- AoE2ScenarioParser
- docs
- resources/docs

nav:
  - AoE2SP:
    - About: "index.md"
    - Installation: "installation.md"
    - Getting Started: "getting_started.md"
    - Hello World: "hello_world.md"
    - Support: "support.md"
  - Cheatsheets:
    - Area: "cheatsheets/area.md"
    - Datasets: "cheatsheets/datasets.md"
    - Data Triggers: "cheatsheets/data_triggers.md"
    - Message: "cheatsheets/message.md"
    - Map: "cheatsheets/map.md"
    - Players: "cheatsheets/players.md"
    - Triggers: "cheatsheets/triggers.md"
    - Units: "cheatsheets/units.md"
    - XS Script: "cheatsheets/xs.md"
  - Examples:
    - Intro: "examples/examples.md"
    - Triggers: "examples/triggers.md"
  - Community:
    - Guides and Resources: "community/resources.md"
    - Tools: "community/tools.md"
    - Projects: "community/projects.md"
  - API Docs:
    - AoE2Scenario: "api_docs/aoe2_scenario.md"
    - MapManager: "api_docs/map_manager.md"
    - MapManagerDE: "api_docs/map_manager_de.md"
    - MessageManager: "api_docs/message_manager.md"
    - PlayerManager: "api_docs/player_manager.md"
    - TriggerManager: "api_docs/trigger_manager.md"
    - TriggerManagerDE: "api_docs/trigger_manager_de.md"
    - UnitManager: "api_docs/unit_manager.md"
    - XsManager: "api_docs/xs_manager_de.md"
    - Unit: "api_docs/unit.md"
    - Player: "api_docs/player.md"
    - TerrainTile: "api_docs/terrain_tile.md"
    - Trigger: "api_docs/trigger.md"
    - TriggerSelect: "api_docs/trigger_select.md"
    - Effect: "api_docs/effect.md"
    - Condition: "api_docs/condition.md"
    - NewEffect: "api_docs/new_effect.md"
    - NewCondition: "api_docs/new_condition.md"
    - Variable: "api_docs/variable.md"
    - Area: "api_docs/area.md"


markdown_extensions:
  - admonition                # Create not and warning boxes        https://squidfunk.github.io/mkdocs-material/reference/admonitions/#admonition
  - pymdownx.caret            # Handling sub- and superscripts      https://facelessuser.github.io/pymdown-extensions/extensions/caret/
  - pymdownx.mark             # Highlighting of text                https://facelessuser.github.io/pymdown-extensions/extensions/mark/
  - pymdownx.tilde            # Strikethrough of text               https://facelessuser.github.io/pymdown-extensions/extensions/tilde/
  - pymdownx.keys             # Add styling keyboard keys           https://facelessuser.github.io/pymdown-extensions/extensions/keys/
  - pymdownx.tabbed           # Tabs                                https://facelessuser.github.io/pymdown-extensions/extensions/tabbed/
  - pymdownx.details          # Collapsable elements                https://facelessuser.github.io/pymdown-extensions/extensions/details/
  - pymdownx.highlight:       # Highlighting code blocks            https://facelessuser.github.io/pymdown-extensions/extensions/highlight/
      linenums: true
  - pymdownx.emoji:           # Emojis                              https://facelessuser.github.io/pymdown-extensions/extensions/emoji/
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite     # Inline code highlighting            https://facelessuser.github.io/pymdown-extensions/extensions/inlinehilite/
  - pymdownx.superfences      # Complicated code fences             https://facelessuser.github.io/pymdown-extensions/extensions/superfences/
  - pymdownx.smartsymbols     # Creating special characters         https://facelessuser.github.io/pymdown-extensions/extensions/smartsymbols/
  - pymdownx.arithmatex:      # Preserve LaTeX math equations       https://facelessuser.github.io/pymdown-extensions/extensions/arithmatex/
      generic: true
  - pymdownx.tasklist:        # Creating Check-able tasklist        https://facelessuser.github.io/pymdown-extensions/extensions/tasklist/
      custom_checkbox: true
      clickable_checkbox: true
  - toc:
      permalink: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - _assets/css/api_docs_extra.css

theme:
  name: material
  language: en
#  favicon: imgs/code.svg
#  icon:
#    logo: fontawesome/solid/code
  features:
    - navigation.tabs
    - search.suggest
    - search.highlight
    - search.share
    - navigation.expand
  font:
    text: Roboto
    code: Fira Code
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode