site_name: AoE2 Scenario Parser Documentation
site_url: https://ksneijders.github.io/AoE2ScenarioParser/
docs_dir: docs/
repo_name: "AoE2ScenarioParser"
repo_url: "https://github.com/KSneijders/AoE2ScenarioParser"
use_directory_urls: true

plugins:
    - search
    - mkdocstrings:
        custom_templates: resources/docs/templates/
        default_handler: python
        handlers:
          python:
            paths: [.]
            options:
              # Options from: https://mkdocstrings.github.io/python/usage/
              show_if_no_docstring: true
              show_category_heading: true
              docstring_style: google
              show_source: true  # Show source code
              show_bases: true  # Show parent classes
              show_submodules: true  # Show the subclasses
              filters: ["!^_[^_]"]
              show_signature: false
              show_signature_annotations: false


watch:
- AoE2ScenarioParser
- docs
- resources/docs

nav:
  - AoE2SP:
    - About:                "index.md"
    - Installation:         "installation.md"
    - Getting Started:      "getting_started.md"
    - Hello World:          "hello_world.md"
    - Support:              "support.md"
  - Cheatsheets:
    - AreaPattern:          "cheatsheets/area.md"
    - Data Triggers:        "cheatsheets/data_triggers.md"
    - Datasets:             "cheatsheets/datasets.md"
    - Message:              "cheatsheets/message.md"
    - Map:                  "cheatsheets/map.md"
    - Players:              "cheatsheets/players.md"
    - Triggers:             "cheatsheets/triggers.md"
    - Units:                "cheatsheets/units.md"
    - XS Script:            "cheatsheets/xs.md"
  - Examples:
    - Intro:                "examples/examples.md"
    - Operations:           "examples/operations.md"
    - Triggers:             "examples/triggers.md"
  - Community:
    - Guides and Resources: "community/resources.md"
    - Tools:                "community/tools.md"
    - Projects:             "community/projects.md"
  - API Docs:
    - AoE2Scenario:         "api_docs/aoe2_scenario.md"
    - AoE2DEScenario:       "api_docs/aoe2_de_scenario.md"
    - Settings:             "api_docs/settings.md"
    - Map:
      - MapManager:         "api_docs/map/map_manager.md"
      - MapManagerDE:       "api_docs/map/map_manager_de.md"
      - TerrainTile:        "api_docs/map/terrain_tile.md"
    - Messages:
      - MessageManager:     "api_docs/messages/message_manager.md"
    - Player:
      - PlayerManager:      "api_docs/player/player_manager.md"
      - PlayerData:         "api_docs/player/player.md"
    - Trigger:
      - TriggerManager:     "api_docs/trigger/trigger_manager.md"
      - TriggerManagerDE:   "api_docs/trigger/trigger_manager_de.md"
      - Trigger:            "api_docs/trigger/trigger.md"
      - Effects:
        - Effect:           "api_docs/trigger/effects/effect.md"
        - NewEffect:        "api_docs/trigger/effects/new_effect.md"
      - Conditions:
        - Condition:        "api_docs/trigger/conditions/condition.md"
        - NewCondition:     "api_docs/trigger/conditions/new_condition.md"
      - Variable:           "api_docs/trigger/variable.md"
      - TriggerSelect:      "api_docs/trigger/trigger_select.md"
      - TriggerCeLock:      "api_docs/trigger/trigger_ce_lock.md"
    - Units:
      - UnitManager:        "api_docs/units/unit_manager.md"
      - UnitManagerDE:      "api_docs/units/unit_manager_de.md"
      - Unit:               "api_docs/units/unit.md"
    - XS:
      - XsManager:          "api_docs/xs/xs_manager_de.md"
    - Support:
      - Area:               "api_docs/support/area.md"
      - AreaAttr:           "api_docs/support/area_attr.md"
      - AreaState:          "api_docs/support/area_state.md"


markdown_extensions:
  - admonition                # Create not and warning boxes        https://squidfunk.github.io/mkdocs-material/reference/admonitions/#admonition
  - pymdownx.caret            # Handling sub- and superscripts      https://facelessuser.github.io/pymdown-extensions/extensions/caret/
  - pymdownx.mark             # Highlighting of text                https://facelessuser.github.io/pymdown-extensions/extensions/mark/
  - pymdownx.tilde            # Strikethrough of text               https://facelessuser.github.io/pymdown-extensions/extensions/tilde/
  - pymdownx.keys             # Add styling keyboard keys           https://facelessuser.github.io/pymdown-extensions/extensions/keys/
  - pymdownx.tabbed           # Tabs                                https://facelessuser.github.io/pymdown-extensions/extensions/tabbed/
  - pymdownx.details          # Collapsable elements                https://facelessuser.github.io/pymdown-extensions/extensions/details/
  - pymdownx.highlight:       # Highlighting code blocks            https://facelessuser.github.io/pymdown-extensions/extensions/highlight/
      linenums: true
  - pymdownx.emoji:           # Emojis                              https://facelessuser.github.io/pymdown-extensions/extensions/emoji/
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite     # Inline code highlighting            https://facelessuser.github.io/pymdown-extensions/extensions/inlinehilite/
  - pymdownx.superfences      # Complicated code fences             https://facelessuser.github.io/pymdown-extensions/extensions/superfences/
  - pymdownx.smartsymbols     # Creating special characters         https://facelessuser.github.io/pymdown-extensions/extensions/smartsymbols/
  - pymdownx.arithmatex:      # Preserve LaTeX math equations       https://facelessuser.github.io/pymdown-extensions/extensions/arithmatex/
      generic: true
  - pymdownx.tasklist:        # Creating Check-able tasklist        https://facelessuser.github.io/pymdown-extensions/extensions/tasklist/
      custom_checkbox: true
      clickable_checkbox: true
  - toc:
      permalink: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - _assets/js/api_docs_toc.js

extra_css:
  - _assets/css/api_docs_extra.css
  - _assets/css/api_docs_toc.css

theme:
  name: material
  language: en
#  favicon: imgs/code.svg
#  icon:
#    logo: fontawesome/solid/code
  features:
    - navigation.tabs
    - search.suggest
    - search.highlight
    - search.share
    - navigation.expand
  font:
    text: Roboto
    code: Fira Code
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode