from src.objects.aoe2_object import AoE2Object


class EffectObject(AoE2Object):
    def __init__(self,
                 effect_type,
                 ai_script_goal,
                 obj_armor_quantity,
                 obj_armor_armor_attack_type,
                 quantity,
                 resource_type,
                 diplomacy,
                 object_list,
                 source_player,
                 target_player,
                 tech,
                 string_id,
                 display_time,
                 trigger_id,
                 location_x,
                 location_y,
                 area_x1,
                 area_y1,
                 area_x2,
                 area_y2,
                 object_group,
                 object_type,
                 instruction_panel_position,
                 attack_stance,
                 time_unit,
                 enabled,
                 victory,
                 food,
                 wood,
                 gold,
                 stone,
                 flash_object,
                 force_research_tech,
                 visibility_state,
                 scroll,
                 operation,
                 target_object_list_id,
                 button_location,
                 ai_signal_value,
                 object_attributes,
                 from_variable,
                 variable,
                 clear_timer,
                 facet,
                 play_sound,
                 message,
                 civ_name,
                 selected_units
                 ):

        super().__init__(locals())

