name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Remove testing and other doc artifacts (As much as feasible at the moment)
        run: |
             find AoE2ScenarioParser/datasets -maxdepth 2 -name '*.py' -exec sed -i 's/    >>> .*//' {} + 
             find AoE2ScenarioParser/datasets -maxdepth 2 -name '*.py' -exec sed -i 's/    <.*: .*>//' {} + 
             find AoE2ScenarioParser/datasets -maxdepth 2 -name '*.py' -exec sed -i 's/    \*\*\(?:\|Examples\|Methods\|Inherited\)\*\*:\?//' {} + 

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: mkdocs.yml
          EXTRA_PACKAGES: build-base
          REQUIREMENTS: requirements/dev.txt
